apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- frontend-deployment.yaml
- service-frontend-lb.yaml
- pvc.yaml
- ingress.yaml

images:
- name: basilvarghese/myapp-frontend
  newName: coitlearning/coit-frontend
  newTag: latest

namePrefix: dev-
nameSuffix: -mumbai